/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.PinController;
import Controllers.SmartCardConnection;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import constants.AppletConstants;
import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import utils.AppUtils;
import utils.ErrorHandleUtils;

/**
 *
 * @author Admin
 */
public class ChangePINCode extends javax.swing.JFrame {
    
    /**
     * Creates new form ChangePINCode
     */
    PinController pinController;
    SmartCardConnection smartCardConnection;

    public ChangePINCode() {
        initComponents();
        pinTextField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mã PIN hiện tại");
        newPINTextField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập mã PIN mới");
        confirmPINTextField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nhập lại mã PIN mới");

        this.setLocationRelativeTo(null);
        smartCardConnection = SmartCardConnection.getInstance();
        pinController = new PinController(smartCardConnection);
//        pinTextField = new JPasswordField(AppletConstants.MAX_PIN_SIZE);
//        confirmPINTextField=new JPasswordField(AppletConstants.MAX_PIN_SIZE);
//        newPINTextField =new JPasswordField(AppletConstants.MAX_PIN_SIZE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        confirmPINTextField = new javax.swing.JPasswordField();
        pinTextField = new javax.swing.JPasswordField();
        newPINTextField = new javax.swing.JPasswordField();
        cancelButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        lb_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thay đổi mã PIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 48, 227, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Xác nhận mã PIN mới");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 250, 139, 33));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã PIN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 133, 90, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã PIN mới");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 90, 33));

        confirmPINTextField.setDoubleBuffered(true);
        getContentPane().add(confirmPINTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 243, 34));
        getContentPane().add(pinTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 243, 34));

        newPINTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPINTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(newPINTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 243, 34));

        cancelButton.setBackground(new java.awt.Color(204, 255, 255));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.setText("Hủy");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
        });
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 322, 102, 35));

        confirmButton.setBackground(new java.awt.Color(204, 255, 255));
        confirmButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmButton.setText("Xác nhận");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 322, 120, 35));

        lb_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/background_600x400.jpg"))); // NOI18N
        getContentPane().add(lb_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeView homeView = new HomeView();
        homeView.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        try {
            char[] pinChars = pinTextField.getPassword();
            char[] newPinChars = newPINTextField.getPassword();
            char[] confirmPinChars = confirmPINTextField.getPassword();
            String pin = new String(pinChars);
            String newPin = new String(newPinChars);
            String confirmPin = new String(confirmPinChars);
            String defaultPIN = AppUtils.byteArrayToText(AppletConstants.DEFAUL_PIN);

            if (pin.isEmpty() || newPin.isEmpty() || confirmPin.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn cần nhập đầy đủ các ô nhập");

            } else if (!newPin.equals(confirmPin)) {
                JOptionPane.showMessageDialog(this, "Mã PIN không trùng khớp");
                newPINTextField.requestFocus();
            } else if (newPin.equals(defaultPIN)) {
                JOptionPane.showMessageDialog(this, "Mã PIN không được trùng với mã mặc định");
                pinTextField.requestFocus();

            } else {
                boolean isSuccess = pinController.changePIN(pin, newPin);
                if (isSuccess) {
//                    UserInfo userInfoView = new UserInfo();
//                    userInfoView.setVisible(true);
                    HomeView homeView = new HomeView();
                    homeView.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Đổi mã PIN không thành công");
                }
            }

        } catch (Exception e) {
            ErrorHandleUtils.handleErrorWithException(this, e, "");
        } finally {
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void newPINTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPINTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPINTextFieldActionPerformed

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        // TODO add your handling code here:
//            cancelButton.setBackground(Color.GREEN); // Đổi màu nền khi hover

    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
        // TODO add your handling code here:
//            cancelButton.setBackground(Color.decode("#CCFFFF")); // Đổi màu nền khi hover

    }//GEN-LAST:event_CancelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePINCode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JPasswordField confirmPINTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lb_bg;
    private javax.swing.JPasswordField newPINTextField;
    private javax.swing.JPasswordField pinTextField;
    // End of variables declaration//GEN-END:variables
}
