/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import com.formdev.flatlaf.FlatLightLaf;
import constants.AppletConstants;
import utils.AppUtils;

/**
 *
 * @author datlogarit
 */
public class ExchangePoints extends javax.swing.JFrame {

    /**
     * Creates new form ExchangePoints
     */
    public ExchangePoints() {
        initComponents();
        this.setLocationRelativeTo(null);
        init();
    }
    private void init(){
        noticeText.setText("* Chú ý: Khách hàng chỉ được chọn một trong các hạn mức trên");
//        noticeText1.setText("Số điểm không được đổi sang số tiền ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        noticeText = new javax.swing.JLabel();
        jScrollPane1 = new scroll.win11.ScrollPaneWin11();
        jPanel1 = new javax.swing.JPanel();
        jLable_img_1K = new javax.swing.JLabel();
        jLabelTile_1K = new javax.swing.JLabel();
        jLabelPoint_1K = new javax.swing.JLabel();
        jLabelDate_1K = new javax.swing.JLabel();
        jLabelDetail_1K = new javax.swing.JLabel();
        jLabel_gift_1K = new javax.swing.JLabel();
        lbbg_1 = new javax.swing.JLabel();
        jLable_img_3 = new javax.swing.JLabel();
        jLabelTile_3 = new javax.swing.JLabel();
        jLabelPoint_3 = new javax.swing.JLabel();
        jLabelDate_3 = new javax.swing.JLabel();
        jLabelDetail_3 = new javax.swing.JLabel();
        jLabel_gift_3 = new javax.swing.JLabel();
        jLable_img_2K = new javax.swing.JLabel();
        jLabelTile_2K = new javax.swing.JLabel();
        jLabelPoint_2K = new javax.swing.JLabel();
        jLabelDate_2K = new javax.swing.JLabel();
        jLabelDetail_2K = new javax.swing.JLabel();
        jLabel_gift_2K = new javax.swing.JLabel();
        lbbg_2 = new javax.swing.JLabel();
        jLable_img_4 = new javax.swing.JLabel();
        jLabelTile_4 = new javax.swing.JLabel();
        jLabelPoint_4 = new javax.swing.JLabel();
        jLabelDate_4 = new javax.swing.JLabel();
        jLabelDetail_4 = new javax.swing.JLabel();
        jLabel_gift_4 = new javax.swing.JLabel();
        lbbg_4 = new javax.swing.JLabel();
        jLable_img_1K1 = new javax.swing.JLabel();
        jLabelTile_1K1 = new javax.swing.JLabel();
        jLabelPoint_1K1 = new javax.swing.JLabel();
        jLabelDate_1K1 = new javax.swing.JLabel();
        jLabelDetail_1K1 = new javax.swing.JLabel();
        jLabel_gift_1K1 = new javax.swing.JLabel();
        lbbg_3 = new javax.swing.JLabel();
        jLable_img_2K1 = new javax.swing.JLabel();
        jLabelTile_2K1 = new javax.swing.JLabel();
        jLabelPoint_2K1 = new javax.swing.JLabel();
        jLabelDate_2K1 = new javax.swing.JLabel();
        jLabelDetail_2K1 = new javax.swing.JLabel();
        jLabel_gift_2K1 = new javax.swing.JLabel();
        lbbg_5 = new javax.swing.JLabel();
        lbbg_6 = new javax.swing.JLabel();
        jbbackground = new javax.swing.JLabel();

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ĐỔI ĐIỂM TÍCH LŨY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Vui lòng chọn một trong các voucher bên dưới");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Tổng điểm hiện có: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Quy đổi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 160, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("2002");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 51));
        jButton3.setText("Quay lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setForeground(new java.awt.Color(0, 0, 51));
        jButton4.setText("Voucher");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 90, -1));

        noticeText.setForeground(new java.awt.Color(255, 51, 51));
        noticeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(noticeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 430, 24));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLable_img_1K.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/voucher_20K_60x60.png"))); // NOI18N
        jPanel1.add(jLable_img_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabelTile_1K.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTile_1K.setText("VOUCHER GIẢM 20K");
        jPanel1.add(jLabelTile_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabelPoint_1K.setText("Cần 10.000 điểm để quy đổi");
        jPanel1.add(jLabelPoint_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabelDate_1K.setText("Date: 15/01/2025 ");
        jPanel1.add(jLabelDate_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabelDetail_1K.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDetail_1K.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDetail_1K.setText("Detail");
        jLabelDetail_1K.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveDetail(evt);
            }
        });
        jPanel1.add(jLabelDetail_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 40, -1));

        jLabel_gift_1K.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/gitf_icon_50x50.jpg"))); // NOI18N
        jPanel1.add(jLabel_gift_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 40));

        lbbg_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/white-background.png"))); // NOI18N
        jPanel1.add(lbbg_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 60));

        jLable_img_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/voucher_100K_60x60.png"))); // NOI18N
        jPanel1.add(jLable_img_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabelTile_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTile_3.setText("VOUCHER GIẢM 100K");
        jPanel1.add(jLabelTile_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabelPoint_3.setText("Cần 10.000 điểm để quy đổi");
        jPanel1.add(jLabelPoint_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabelDate_3.setText("Date: 15/01/2025 ");
        jPanel1.add(jLabelDate_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabelDetail_3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDetail_3.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDetail_3.setText("Detail");
        jPanel1.add(jLabelDetail_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 40, -1));

        jLabel_gift_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/gitf_icon_50x50.jpg"))); // NOI18N
        jPanel1.add(jLabel_gift_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, 40));

        jLable_img_2K.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/voucher_50K_60x60.png"))); // NOI18N
        jPanel1.add(jLable_img_2K, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabelTile_2K.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTile_2K.setText("VOUCHER GIẢM 50K");
        jPanel1.add(jLabelTile_2K, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabelPoint_2K.setText("Cần 10.000 điểm để quy đổi");
        jPanel1.add(jLabelPoint_2K, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, -1, -1));

        jLabelDate_2K.setText("Date: 15/01/2025 ");
        jPanel1.add(jLabelDate_2K, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabelDetail_2K.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDetail_2K.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDetail_2K.setText("Detail");
        jPanel1.add(jLabelDetail_2K, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 40, -1));

        jLabel_gift_2K.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/gitf_icon_50x50.jpg"))); // NOI18N
        jPanel1.add(jLabel_gift_2K, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 40));

        lbbg_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/white-background.png"))); // NOI18N
        jPanel1.add(lbbg_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 290, 60));

        jLable_img_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/voucher_200K_60x60.png"))); // NOI18N
        jPanel1.add(jLable_img_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabelTile_4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTile_4.setText("VOUCHER GIẢM 200K");
        jPanel1.add(jLabelTile_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        jLabelPoint_4.setText("Cần 10.000 điểm để quy đổi");
        jPanel1.add(jLabelPoint_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabelDate_4.setText("Date: 15/01/2025 ");
        jPanel1.add(jLabelDate_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabelDetail_4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDetail_4.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDetail_4.setText("Detail");
        jPanel1.add(jLabelDetail_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 40, -1));

        jLabel_gift_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/gitf_icon_50x50.jpg"))); // NOI18N
        jPanel1.add(jLabel_gift_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, 40));

        lbbg_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/white-background.png"))); // NOI18N
        jPanel1.add(lbbg_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 290, 60));

        jLable_img_1K1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/voucher_20K_60x60.png"))); // NOI18N
        jPanel1.add(jLable_img_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabelTile_1K1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTile_1K1.setText("VOUCHER GIẢM 20K");
        jPanel1.add(jLabelTile_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabelPoint_1K1.setText("Cần 10.000 điểm để quy đổi");
        jPanel1.add(jLabelPoint_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabelDate_1K1.setText("Date: 15/01/2025 ");
        jPanel1.add(jLabelDate_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabelDetail_1K1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDetail_1K1.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDetail_1K1.setText("Detail");
        jLabelDetail_1K1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDetail_1K1moveDetail(evt);
            }
        });
        jPanel1.add(jLabelDetail_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 40, -1));

        jLabel_gift_1K1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/gitf_icon_50x50.jpg"))); // NOI18N
        jPanel1.add(jLabel_gift_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, 40));

        lbbg_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/white-background.png"))); // NOI18N
        jPanel1.add(lbbg_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 290, 60));

        jLable_img_2K1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/voucher_50K_60x60.png"))); // NOI18N
        jPanel1.add(jLable_img_2K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabelTile_2K1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTile_2K1.setText("VOUCHER GIẢM 50K");
        jPanel1.add(jLabelTile_2K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jLabelPoint_2K1.setText("Cần 10.000 điểm để quy đổi");
        jPanel1.add(jLabelPoint_2K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));

        jLabelDate_2K1.setText("Date: 15/01/2025 ");
        jPanel1.add(jLabelDate_2K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        jLabelDetail_2K1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDetail_2K1.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDetail_2K1.setText("Detail");
        jPanel1.add(jLabelDetail_2K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 40, -1));

        jLabel_gift_2K1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/gitf_icon_50x50.jpg"))); // NOI18N
        jPanel1.add(jLabel_gift_2K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, 40));

        lbbg_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/white-background.png"))); // NOI18N
        jPanel1.add(lbbg_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 290, 60));

        lbbg_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/white-background.png"))); // NOI18N
        jPanel1.add(lbbg_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 290, 60));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 700, 190));

        jbbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/background_800x533.jpg"))); // NOI18N
        getContentPane().add(jbbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeView homeView = new HomeView();
        homeView.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HomeView homeView = new HomeView();
        homeView.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        VoucherList vouchePage = new VoucherList();
        vouchePage.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void moveDetail(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveDetail
        // TODO add your handling code here:
         this.dispose();
        DetailVoucher detailVoucher = new DetailVoucher();
        detailVoucher.setVisible(true);
    }//GEN-LAST:event_moveDetail

    private void jLabelDetail_1K1moveDetail(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDetail_1K1moveDetail
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelDetail_1K1moveDetail

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExchangePoints().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDate_1K;
    private javax.swing.JLabel jLabelDate_1K1;
    private javax.swing.JLabel jLabelDate_2K;
    private javax.swing.JLabel jLabelDate_2K1;
    private javax.swing.JLabel jLabelDate_3;
    private javax.swing.JLabel jLabelDate_4;
    private javax.swing.JLabel jLabelDetail_1K;
    private javax.swing.JLabel jLabelDetail_1K1;
    private javax.swing.JLabel jLabelDetail_2K;
    private javax.swing.JLabel jLabelDetail_2K1;
    private javax.swing.JLabel jLabelDetail_3;
    private javax.swing.JLabel jLabelDetail_4;
    private javax.swing.JLabel jLabelPoint_1K;
    private javax.swing.JLabel jLabelPoint_1K1;
    private javax.swing.JLabel jLabelPoint_2K;
    private javax.swing.JLabel jLabelPoint_2K1;
    private javax.swing.JLabel jLabelPoint_3;
    private javax.swing.JLabel jLabelPoint_4;
    private javax.swing.JLabel jLabelTile_1K;
    private javax.swing.JLabel jLabelTile_1K1;
    private javax.swing.JLabel jLabelTile_2K;
    private javax.swing.JLabel jLabelTile_2K1;
    private javax.swing.JLabel jLabelTile_3;
    private javax.swing.JLabel jLabelTile_4;
    private javax.swing.JLabel jLabel_gift_1K;
    private javax.swing.JLabel jLabel_gift_1K1;
    private javax.swing.JLabel jLabel_gift_2K;
    private javax.swing.JLabel jLabel_gift_2K1;
    private javax.swing.JLabel jLabel_gift_3;
    private javax.swing.JLabel jLabel_gift_4;
    private javax.swing.JLabel jLable_img_1K;
    private javax.swing.JLabel jLable_img_1K1;
    private javax.swing.JLabel jLable_img_2K;
    private javax.swing.JLabel jLable_img_2K1;
    private javax.swing.JLabel jLable_img_3;
    private javax.swing.JLabel jLable_img_4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbbackground;
    private javax.swing.JLabel lbbg_1;
    private javax.swing.JLabel lbbg_2;
    private javax.swing.JLabel lbbg_3;
    private javax.swing.JLabel lbbg_4;
    private javax.swing.JLabel lbbg_5;
    private javax.swing.JLabel lbbg_6;
    private javax.swing.JLabel noticeText;
    // End of variables declaration//GEN-END:variables
}
