/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DAO.PointTransactionDao;
import Models.PointsTransaction;
import Models.UserData;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class HistoryForm extends javax.swing.JFrame {

    /**
     * Creates new form HistoryForm
     */
    PointTransactionDao pointTransactionDao;
    int userId;
    List<PointsTransaction> listTransactions;
    DefaultTableModel defaultTableModel;
    java.sql.Date selectedDate;
    UserData userData;

    public HistoryForm(UserData userData) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.userData = userData;
        pointTransactionDao = PointTransactionDao.getInstance();
        defaultTableModel = new DefaultTableModel(new Object[][]{},
                new String[]{
                    "STT", "Loại giao dịch", "Số điểm", "Mô tả", "Loại", "Thời gian"
                }
        );
        transactionTable.setModel(defaultTableModel);
        selectedDate = null;
        listTransactions = new ArrayList<>();
        initViews();
        initListTransaction();
        onListenDateChanges();

    }

    private HistoryForm() {
    }

    private void initListTransaction() {

        try {
            listTransactions = pointTransactionDao.getTransactionsByUserId(userData.getId(), selectedDate);
        } catch (SQLException ex) {
//            Logger.getLogger(HistoryForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(HistoryForm.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            display();
        }
    }

    private void initViews() {
//        transactionTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
//        transactionTable.getTableHeader().setOpaque(false);
//        transactionTable.getTableHeader().setBackground(new Color(204, 255, 255));
//        transactionTable.getTableHeader().setForeground(new Color(255, 255, 255));
//        transactionTable.setRowHeight(25);
        // Khởi tạo JTable với dữ liệu trống và tiêu đề cột
//        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
//                new Object[][]{}, // Dữ liệu trống
//                new String[]{
//                    "STT", "Loại giao dịch", "Số điểm", "Mô tả", "Loại", "Thời gian"
//                }
//        ));
//        transactionTable.set
    }

    public void display() {
        for (int i = 0; i < listTransactions.size(); i++) {
            showTable((i + 1), listTransactions.get(i));
        }
    }

    public void showTable(int index, PointsTransaction h) {
        defaultTableModel.addRow(new Object[]{
            index, h.getTransactionType(), h.getPoints(), h.getDescription(), h.getResourceType(), h.getCreatedAt()
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        resetButton = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lịch sử giao dịch");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 17, 227, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Lọc theo ngày");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 30));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 74, 200, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setForeground(new java.awt.Color(0, 0, 51));
        jButton3.setText("Quay lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(transactionTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 620, 280));

        resetButton.setText("Đặt lại");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 110, 30));

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/background_900x600.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HomeView homeView = new HomeView();
        this.dispose();
        homeView.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        jDateChooser1.setDate(null);
        selectedDate = null;
        defaultTableModel.setNumRows(0);
        initListTransaction();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void onListenDateChanges() {
        jDateChooser1.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if (jDateChooser1.getDate() != null) {
                    defaultTableModel.setNumRows(0);
                    selectedDate = new java.sql.Date(jDateChooser1.getDate().getTime());
                    initListTransaction();
                }
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JButton resetButton;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables
}
