/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.SmartCardConnection;
import Controllers.UserDataController;
import DAO.UserDao;
import Models.UserData;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.formdev.flatlaf.FlatLightLaf;
import utils.ErrorHandleUtils;

/**
 *
 * @author Admin
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    
    UserDataController userDataController;
    SmartCardConnection smartCardConnection;
    UserData userData;
    UserDao userDao;
    public HomeView() {
        initComponents();
        this.setLocationRelativeTo(null);
        smartCardConnection = SmartCardConnection.getInstance();
        userDataController = new UserDataController(smartCardConnection);
        userDao = UserDao.getInstance();
          try {
            initUserData();
        } catch (Exception ex) {
            Logger.getLogger(UserInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public HomeView(UserData user) {
        initComponents();
        this.setLocationRelativeTo(null);
        smartCardConnection = SmartCardConnection.getInstance();
        userDataController = new UserDataController(smartCardConnection);
        userDao = UserDao.getInstance();
        userData = user;
        loyaltyPointsTextView.setText(String.valueOf(userData.getPoints()));
    }
    
     private void initUserData() throws Exception{
//        userData = userDataController.readUserData();
        UserData cardUserData = userDataController.readUserData();
        userData = userDao.getUserById(cardUserData.getId());
        loyaltyPointsTextView.setText(String.valueOf(userData.getPoints()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        loyaltyPointsTextView = new javax.swing.JLabel();
        userInfoButton = new javax.swing.JButton();
        changePINButton = new javax.swing.JButton();
        redeemPointButton = new javax.swing.JButton();
        transactionHistoryButton = new javax.swing.JButton();
        disconnectButton = new javax.swing.JButton();
        chargePointButton = new javax.swing.JButton();
        lb_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Màn hình chính");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 227, 37));

        jPanel1.setBackground(new java.awt.Color(49, 145, 174));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Điểm tích lũy hiện tại");

        loyaltyPointsTextView.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loyaltyPointsTextView.setForeground(new java.awt.Color(255, 255, 255));
        loyaltyPointsTextView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loyaltyPointsTextView.setText("400");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loyaltyPointsTextView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loyaltyPointsTextView, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 150));

        userInfoButton.setBackground(new java.awt.Color(176, 213, 199));
        userInfoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userInfoButton.setForeground(new java.awt.Color(0, 51, 51));
        userInfoButton.setText("Thông tin cá nhân");
        userInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInfoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(userInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 88, 155, 40));

        changePINButton.setBackground(new java.awt.Color(176, 213, 199));
        changePINButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        changePINButton.setForeground(new java.awt.Color(0, 0, 51));
        changePINButton.setText("Đổi PIN");
        changePINButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePINButtonActionPerformed(evt);
            }
        });
        getContentPane().add(changePINButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 294, 155, 40));

        redeemPointButton.setBackground(new java.awt.Color(176, 213, 199));
        redeemPointButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        redeemPointButton.setForeground(new java.awt.Color(0, 51, 51));
        redeemPointButton.setText("Đổi điểm");
        redeemPointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redeemPointButtonActionPerformed(evt);
            }
        });
        getContentPane().add(redeemPointButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 88, 155, 40));

        transactionHistoryButton.setBackground(new java.awt.Color(176, 213, 199));
        transactionHistoryButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        transactionHistoryButton.setForeground(new java.awt.Color(0, 51, 51));
        transactionHistoryButton.setText("Lịch sử giao dịch");
        transactionHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionHistoryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(transactionHistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 191, 155, 40));

        disconnectButton.setBackground(new java.awt.Color(238, 108, 77));
        disconnectButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        disconnectButton.setForeground(new java.awt.Color(51, 51, 51));
        disconnectButton.setText("Ngắt kết nối");
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });
        getContentPane().add(disconnectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 288, 155, 40));

        chargePointButton.setBackground(new java.awt.Color(176, 213, 199));
        chargePointButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chargePointButton.setForeground(new java.awt.Color(0, 51, 51));
        chargePointButton.setText("Tích điểm");
        chargePointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargePointButtonActionPerformed(evt);
            }
        });
        getContentPane().add(chargePointButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 187, 155, 40));

        lb_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/background_800x533.jpg"))); // NOI18N
        getContentPane().add(lb_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePINButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePINButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ChangePINCode changePinView = new ChangePINCode();
        changePinView.setVisible(true);
        
    }//GEN-LAST:event_changePINButtonActionPerformed

    private void transactionHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionHistoryButtonActionPerformed
        this.dispose();
        HistoryForm historyForm = new HistoryForm(userData.getId());
        historyForm.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionHistoryButtonActionPerformed

    private void userInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInfoButtonActionPerformed
        // TODO add your handling code here:
        try {
//           UserData userData = userDataController.readUserData();
            UserInfo userInfoView = new UserInfo();
            this.dispose();
            userInfoView.setVisible(true);
           
        } catch (Exception e) {
            ErrorHandleUtils.handleErrorWithException(this, e, "Lỗi ko đọc được thông tin 1");
        } finally {
        }
    }//GEN-LAST:event_userInfoButtonActionPerformed

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
        // TODO add your handling code here:
        smartCardConnection.disconnect();
        this.dispose();
        ConnectionForm connectionForm = new ConnectionForm();
        connectionForm.setVisible(true);
    }//GEN-LAST:event_disconnectButtonActionPerformed

    private void chargePointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargePointButtonActionPerformed
        // TODO add your handling code here:
        AccummulatePoints accummulatePoints = new AccummulatePoints(userData);
        this.dispose();
        accummulatePoints.setVisible(true);
    }//GEN-LAST:event_chargePointButtonActionPerformed

    private void redeemPointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redeemPointButtonActionPerformed
        // TODO add your handling code here:
        ExchangePoints exchangePoints = new ExchangePoints(userData);
        this.dispose();
        exchangePoints.setVisible(true);
    }//GEN-LAST:event_redeemPointButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changePINButton;
    private javax.swing.JButton chargePointButton;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_bg;
    private javax.swing.JLabel loyaltyPointsTextView;
    private javax.swing.JButton redeemPointButton;
    private javax.swing.JButton transactionHistoryButton;
    private javax.swing.JButton userInfoButton;
    // End of variables declaration//GEN-END:variables
}
