/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.PinController;
import Controllers.SmartCardConnection;
import Controllers.UserDataController;
import constants.AppletConstants;
import java.util.Arrays;
import javax.swing.JOptionPane;
import utils.AppUtils;
import utils.ErrorHandleUtils;

/**
 *
 * @author Admin
 */
public class InitView extends javax.swing.JFrame {

    /**
     * Creates new form InitView
     */
    SmartCardConnection smartCardConnection;
    PinController pinController;
    UserDataController userDataController;

    public InitView() {
        initComponents();
        smartCardConnection= SmartCardConnection.getInstance();
        pinController=new PinController(smartCardConnection);
        userDataController = new UserDataController(smartCardConnection);
        this.setLocationRelativeTo(null);
        init();
    }
    private void init(){
        String pinString = AppUtils.byteArrayToText(AppletConstants.DEFAUL_PIN);
        noticeText.setText("* Chú ý: Nếu lần đầu dùng thẻ thì mã PIN mặc định là "+pinString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginButton = new javax.swing.JButton();
        pinTextField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        noticeText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bgEnterPin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginButton.setBackground(new java.awt.Color(176, 213, 199));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(0, 51, 51));
        loginButton.setText("Đăng nhập");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 140, 41));

        pinTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 20));
        pinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(pinTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 190, 39));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 63, 39));

        noticeText.setForeground(new java.awt.Color(255, 51, 51));
        noticeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(noticeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 380, 24));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("HỆ THỐNG TÍCH ĐIỂM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("WELCOME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        bgEnterPin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/background_600x400.jpg"))); // NOI18N
        getContentPane().add(bgEnterPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        try {
            if(pinTextField.getPassword().length < AppletConstants.MAX_PIN_SIZE || pinTextField.getPassword().length > AppletConstants.MAX_PIN_SIZE){
                JOptionPane.showMessageDialog(this, "Độ dài mã PIN không hợp lệ");
            }else{
               char[] pinChars = pinTextField.getPassword();
               String pin = new String(pinChars);
               boolean isVerified =  pinController.verifyPin(pin);
               if(isVerified){
//                   JOptionPane.showMessageDialog(this, "Thành công");
                    this.dispose();
                    boolean isInitialized = userDataController.checkExistedData();
                    if(isInitialized){
                        HomeView homeView= new HomeView();
                        homeView.setVisible(true);
                    }else{
                        RegisterCard registerCard = new RegisterCard();
                        registerCard.setVisible(true);
                    }
                    
               }else{
                   JOptionPane.showMessageDialog(this, "Sai mã PIN");
               }
            }
        } catch (Exception e) {
             ErrorHandleUtils.handleErrorWithException(this, e, "");
        } finally {
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void pinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InitView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgEnterPin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel noticeText;
    private javax.swing.JPasswordField pinTextField;
    // End of variables declaration//GEN-END:variables
}
