/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author datlogarit
 */
public class VoucherList extends javax.swing.JFrame {

    /**
     * Creates new form voucherPage
     */
    public VoucherList() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new scroll.win11.ScrollPaneWin11();
        jPanel1 = new javax.swing.JPanel();
        jLable_img_1K = new javax.swing.JLabel();
        jLabelTile_1K = new javax.swing.JLabel();
        jLabelPoint_1K = new javax.swing.JLabel();
        jLabelDate_1K = new javax.swing.JLabel();
        jLabelDetail_1K = new javax.swing.JLabel();
        jLabel_gift_1K = new javax.swing.JLabel();
        lbbg_1 = new javax.swing.JLabel();
        jLabelTile_1K1 = new javax.swing.JLabel();
        jLabelDate_1K1 = new javax.swing.JLabel();
        jLabel_gift_1K1 = new javax.swing.JLabel();
        jLable_img_1K1 = new javax.swing.JLabel();
        jLabelDetail_1K1 = new javax.swing.JLabel();
        jLabelPoint_1K1 = new javax.swing.JLabel();
        lbbg_2 = new javax.swing.JLabel();
        jLable_img_1K2 = new javax.swing.JLabel();
        jLabelTile_1K2 = new javax.swing.JLabel();
        jLabelPoint_1K2 = new javax.swing.JLabel();
        jLabelDate_1K2 = new javax.swing.JLabel();
        jLabelDetail_1K2 = new javax.swing.JLabel();
        jLabel_gift_1K2 = new javax.swing.JLabel();
        lbbg_3 = new javax.swing.JLabel();
        jLable_img_1K3 = new javax.swing.JLabel();
        jLabelTile_1K3 = new javax.swing.JLabel();
        jLabelPoint_1K3 = new javax.swing.JLabel();
        jLabelDate_1K3 = new javax.swing.JLabel();
        jLabelDetail_1K3 = new javax.swing.JLabel();
        jLabel_gift_1K3 = new javax.swing.JLabel();
        lbbg_4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jbbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Voucher");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 227, 37));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Loại voucher");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có thể dùng", "Sắp hết hạn", "Không khả dụng" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLable_img_1K.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/voucher_20K_60x60.png"))); // NOI18N
        jPanel1.add(jLable_img_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jLabelTile_1K.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTile_1K.setText("VOUCHER GIẢM 20K");
        jPanel1.add(jLabelTile_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));

        jLabelPoint_1K.setText("Cần 10.000 điểm để quy đổi");
        jPanel1.add(jLabelPoint_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabelDate_1K.setText("Date: 15/01/2025 ");
        jPanel1.add(jLabelDate_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabelDetail_1K.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDetail_1K.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDetail_1K.setText("Detail");
        jLabelDetail_1K.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveDetail(evt);
            }
        });
        jPanel1.add(jLabelDetail_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 40, -1));

        jLabel_gift_1K.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/gitf_icon_50x50.jpg"))); // NOI18N
        jPanel1.add(jLabel_gift_1K, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 50, 40));

        lbbg_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/white-background.png"))); // NOI18N
        lbbg_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 4, 1));
        jPanel1.add(lbbg_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 60));

        jLabelTile_1K1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTile_1K1.setText("VOUCHER GIẢM 20K");
        jPanel1.add(jLabelTile_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabelDate_1K1.setText("Date: 15/01/2025 ");
        jPanel1.add(jLabelDate_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel_gift_1K1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/gitf_icon_50x50.jpg"))); // NOI18N
        jPanel1.add(jLabel_gift_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, 40));

        jLable_img_1K1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/voucher_20K_60x60.png"))); // NOI18N
        jPanel1.add(jLable_img_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 60));

        jLabelDetail_1K1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDetail_1K1.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDetail_1K1.setText("Detail");
        jLabelDetail_1K1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveDetail(evt);
            }
        });
        jPanel1.add(jLabelDetail_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 40, -1));

        jLabelPoint_1K1.setText("Cần 10.000 điểm để quy đổi");
        jPanel1.add(jLabelPoint_1K1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        lbbg_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/white-background.png"))); // NOI18N
        jPanel1.add(lbbg_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 290, 60));

        jLable_img_1K2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/voucher_20K_60x60.png"))); // NOI18N
        jPanel1.add(jLable_img_1K2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 60, 60));

        jLabelTile_1K2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTile_1K2.setText("VOUCHER GIẢM 20K");
        jPanel1.add(jLabelTile_1K2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabelPoint_1K2.setText("Cần 10.000 điểm để quy đổi");
        jPanel1.add(jLabelPoint_1K2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabelDate_1K2.setText("Date: 15/01/2025 ");
        jPanel1.add(jLabelDate_1K2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabelDetail_1K2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDetail_1K2.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDetail_1K2.setText("Detail");
        jLabelDetail_1K2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveDetail(evt);
            }
        });
        jPanel1.add(jLabelDetail_1K2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 40, -1));

        jLabel_gift_1K2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/gitf_icon_50x50.jpg"))); // NOI18N
        jPanel1.add(jLabel_gift_1K2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 50, 40));

        lbbg_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/white-background.png"))); // NOI18N
        jPanel1.add(lbbg_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 290, 60));

        jLable_img_1K3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/voucher_20K_60x60.png"))); // NOI18N
        jPanel1.add(jLable_img_1K3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 60, 60));

        jLabelTile_1K3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTile_1K3.setText("VOUCHER GIẢM 20K");
        jPanel1.add(jLabelTile_1K3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabelPoint_1K3.setText("Cần 10.000 điểm để quy đổi");
        jPanel1.add(jLabelPoint_1K3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabelDate_1K3.setText("Date: 15/01/2025 ");
        jPanel1.add(jLabelDate_1K3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabelDetail_1K3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDetail_1K3.setForeground(new java.awt.Color(255, 51, 51));
        jLabelDetail_1K3.setText("Detail");
        jLabelDetail_1K3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveDetail(evt);
            }
        });
        jPanel1.add(jLabelDetail_1K3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 40, -1));

        jLabel_gift_1K3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/gitf_icon_50x50.jpg"))); // NOI18N
        jPanel1.add(jLabel_gift_1K3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 50, 40));

        lbbg_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/white-background.png"))); // NOI18N
        jPanel1.add(lbbg_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, 60));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 310, 210));

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, -1));

        jbbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/background_600x400.jpg"))); // NOI18N
        getContentPane().add(jbbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ExchangePoints exchangePoints = new ExchangePoints();
        exchangePoints.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void moveDetail(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveDetail
        this.dispose();
        DetailVoucher detailVoucher = new DetailVoucher();
        detailVoucher.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_moveDetail

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoucherList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDate_1K;
    private javax.swing.JLabel jLabelDate_1K1;
    private javax.swing.JLabel jLabelDate_1K2;
    private javax.swing.JLabel jLabelDate_1K3;
    private javax.swing.JLabel jLabelDetail_1K;
    private javax.swing.JLabel jLabelDetail_1K1;
    private javax.swing.JLabel jLabelDetail_1K2;
    private javax.swing.JLabel jLabelDetail_1K3;
    private javax.swing.JLabel jLabelPoint_1K;
    private javax.swing.JLabel jLabelPoint_1K1;
    private javax.swing.JLabel jLabelPoint_1K2;
    private javax.swing.JLabel jLabelPoint_1K3;
    private javax.swing.JLabel jLabelTile_1K;
    private javax.swing.JLabel jLabelTile_1K1;
    private javax.swing.JLabel jLabelTile_1K2;
    private javax.swing.JLabel jLabelTile_1K3;
    private javax.swing.JLabel jLabel_gift_1K;
    private javax.swing.JLabel jLabel_gift_1K1;
    private javax.swing.JLabel jLabel_gift_1K2;
    private javax.swing.JLabel jLabel_gift_1K3;
    private javax.swing.JLabel jLable_img_1K;
    private javax.swing.JLabel jLable_img_1K1;
    private javax.swing.JLabel jLable_img_1K2;
    private javax.swing.JLabel jLable_img_1K3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jbbackground;
    private javax.swing.JLabel lbbg_1;
    private javax.swing.JLabel lbbg_2;
    private javax.swing.JLabel lbbg_3;
    private javax.swing.JLabel lbbg_4;
    // End of variables declaration//GEN-END:variables
}
